### ISSUE TITLE
Key detection

### ISSUE THREAD

**Issue by geigerzaehler** [beetbox/beets#662]
This is a meta issue for all the requests related to key detection of songs.

To provide this feature there several things we have to do.
- [x] Add the `initialkey` tag to `MediaFile` and beets core. The tag specification is [here](https://github.com/sampsyo/beets/issues/637#issuecomment-39528023) and there is already some [test code](https://github.com/geigerzaehler/beets/blob/extendable-mediafile/test/test_mediafile.py#L258) using this.
- [x] Extend the _echonest_ plugin to retrieve the initial key and store it. This was previously discussed in #279.
- [x] Write a plugin that uses [a third party tool](http://www.ibrahimshaath.co.uk/keyfinder/) to detect the key and store it. Also discussed in #279 
- [x] Agree on a format for storing the key and add code to the plugins to convert to that format.
- [ ] [Collect information](https://github.com/sampsyo/beets/wiki/Key-Information-for-DJ-Software) on where and how DJ software (Serato, Traktor, Mixed In Key) reads and stores the key information.
